### ISSUE TITLE
Deno.dlopen is not a function

### ISSUE THREAD

**Issue by targetlucked69** [sigmaSd/reedline-deno#2]
I have this

```bash
~/tmp/deno-test via  v18.4.0
❯ deno --version
deno 1.23.3 (release, aarch64-apple-darwin)
v8 10.4.132.8
typescript 4.7.4
```

and a simple snippet

```ts
import { ReedLine } from "https://deno.land/x/reedline_deno@0.9.0/src/mod.ts";

const rl = await ReedLine.create();

while (true) {
  const line = await rl.readLine({
    render_prompt_left: "> ",
    render_prompt_right: "<",
  });
  if (line.signal === "CtrlC") {
    console.log("CtrlC");
    break;
  }
  if (line.signal === "CtrlD") {
    console.log("CtrlD");
    break;
  }
  console.log(line.value);
}
```

and when I run I get this error

```bash
~/tmp/deno-test via  v18.4.0
❯ deno run ./index.ts
⚠️  ️Deno requests env access to "RUST_LIB_PATH". Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests env access to "DENO_DIR". Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests env access to "HOME". Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests read access to "/Users/jeremy/Library/Caches/deno/plug/https/github.com/e85bb8e5874e08ea149f850dc64f34cfcca67f1abebc5e1079d2285714febf4a.dylib". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests read access to "/Users/jeremy/Library/Caches/deno/plug/https/github.com". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
error: Uncaught (in promise) TypeError: Deno.dlopen is not a function
  return Deno.dlopen(file, symbols);
              ^
    at Module.prepare (https://deno.land/x/plug@0.5.1/plug.ts:106:15)
    at async Function.new (https://deno.land/x/reedline_deno@0.8.0/reedline.ts:34:17)
    at async file:///Users/jeremy/tmp/deno-test/index.ts:3:12
```

**Comment by targetlucked69** [comment]
Also I tried cloning the project, and running `deno task example` gave me this:

```bash
reedline-deno on  master via 🦕 v1.23.3 via  v18.4.0
❯ deno task example
Warning deno task is unstable and may drastically change in the future
Task example deno task build && deno task example:nobuild
Warning deno task is unstable and may drastically change in the future
Task build cd src-rust; cargo build
  Downloaded quote v1.0.18
  Downloaded strum v0.24.0
  Downloaded strum_macros v0.24.0
  Downloaded unicode-ident v1.0.0
  Downloaded rustversion v1.0.6
  Downloaded proc-macro2 v1.0.39
  Downloaded serde_derive v1.0.137
  Downloaded smallvec v1.8.0
  Downloaded syn v1.0.96
  Downloaded serde v1.0.137
  Downloaded nanoserde-derive v0.1.18
  Downloaded nanoserde v0.1.30
  Downloaded io-lifetimes v0.6.1
  Downloaded mio v0.8.3
  Downloaded fd-lock v3.0.5
  Downloaded rustix v0.34.8
  Downloaded 16 crates (996.3 KB) in 1.12s
   Compiling libc v0.2.126
   Compiling proc-macro2 v1.0.39
   Compiling unicode-ident v1.0.0
   Compiling autocfg v1.1.0
   Compiling syn v1.0.96
   Compiling cfg-if v1.0.0
   Compiling log v0.4.17
   Compiling parking_lot_core v0.9.3
   Compiling io-lifetimes v0.6.1
   Compiling signal-hook v0.3.14
   Compiling serde_derive v1.0.137
   Compiling smallvec v1.8.0
   Compiling rustix v0.34.8
   Compiling scopeguard v1.1.0
   Compiling serde v1.0.137
   Compiling bitflags v1.3.2
   Compiling rustversion v1.0.6
   Compiling arrayvec v0.5.2
   Compiling utf8parse v0.2.0
   Compiling either v1.7.0
   Compiling overload v0.1.1
   Compiling heck v0.4.0
   Compiling unicode-segmentation v1.9.0
   Compiling unicode-width v0.1.9
   Compiling nanoserde-derive v0.1.18
   Compiling strum v0.24.0
   Compiling num-traits v0.2.15
   Compiling lock_api v0.4.7
   Compiling num-integer v0.1.45
   Compiling nu-ansi-term v0.46.0
   Compiling itertools v0.10.3
   Compiling nanoserde v0.1.30
   Compiling quote v1.0.18
   Compiling vte_generate_state_changes v0.1.1
   Compiling vte v0.10.1
   Compiling signal-hook-registry v1.4.0
   Compiling mio v0.8.3
   Compiling errno v0.2.8
   Compiling time v0.1.44
   Compiling signal-hook-mio v0.2.3
   Compiling parking_lot v0.12.1
   Compiling strip-ansi-escapes v0.1.1
   Compiling chrono v0.4.19
   Compiling fd-lock v3.0.5
   Compiling thiserror-impl v1.0.31
   Compiling strum_macros v0.24.0
   Compiling thiserror v1.0.31
   Compiling crossterm v0.23.2
   Compiling reedline v0.8.0
   Compiling reedline-rust v0.1.0 (/Users/jeremy/tmp/reedline-deno/src-rust)
    Finished dev [unoptimized + debuginfo] target(s) in 10.44s
Warning deno task is unstable and may drastically change in the future
Task example:nobuild export RUST_LIB_PATH=$CARGO_TARGET_DIR/debug && deno run --unstable -A example.ts
Download /debug/libreedline_rust.dylib
error: Uncaught (in promise) CacheError: /debug/libreedline_rust.dylib is not valid.
    throw new CacheError(`${path} is not valid.`);
          ^
    at protocolFile (https://deno.land/x/cache@0.2.13/file_fetcher.ts:12:11)
    at async fetchFile (https://deno.land/x/cache@0.2.13/file_fetcher.ts:41:14)
    at async FileWrapper.fetch (https://deno.land/x/cache@0.2.13/file.ts:95:18)
    at async FileWrapper.get (https://deno.land/x/cache@0.2.13/file.ts:113:12)
    at async cache (https://deno.land/x/cache@0.2.13/cache.ts:67:10)
    at async Wrapper.cache (https://deno.land/x/cache@0.2.13/cache.ts:21:12)
    at async download (https://deno.land/x/plug@0.5.1/plug.ts:96:16)
    at async Module.prepare (https://deno.land/x/plug@0.5.1/plug.ts:105:16)
    at async Function.create (file:///Users/jeremy/tmp/reedline-deno/src/mod.ts:45:17)
    at async file:///Users/jeremy/tmp/reedline-deno/example.ts:3:12
```

**Comment by sigmaSd** [comment]
To answer your original question you need to run with --unstable
`deno run --unstable file.ts`

For the second part I'll need to think about and figure it out

**Comment by sigmaSd** [comment]
The second part is probably because I'm using CARGO_TARGET_DIR which might not be set in your system

I guess I can improve the situation by falling back to a local target directory

**Comment by targetlucked69** [comment]
> To answer your original question you need to run with --unstable `deno run --unstable file.ts`
> 
> For the second part I'll need to think about and figure it out

With the `--unstable` flag:

```bash
~/tmp/deno-test via  v18.4.0 
❯ deno run --unstable ./index.ts
⚠️  ️Deno requests env access to "RUST_LIB_PATH". Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests env access to "DENO_DIR". Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests env access to "HOME". Run again with --allow-env to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests read access to "/Users/jeremy/Library/Caches/deno/plug/https/github.com/b7596db53c234aac58f8b7e133433d179203982c15e3f2e13c5de63c4543a9bd.dylib". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests read access to "/Users/jeremy/Library/Caches/deno/plug/https/github.com". Run again with --allow-read to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
⚠️  ️Deno requests ffi access to "/Users/jeremy/Library/Caches/deno/plug/https/github.com/b7596db53c234aac58f8b7e133433d179203982c15e3f2e13c5de63c4543a9bd.dylib". Run again with --allow-ffi to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]  y
error: Uncaught (in promise) Error: Could not open library: Could not open library: dlopen(/Users/jeremy/Library/Caches/deno/plug/https/github.com/b7596db53c234aac58f8b7e133433d179203982c15e3f2e13c5de63c4543a9bd.dylib, 0x0005): tried: '/Users/jeremy/Library/Caches/deno/plug/https/github.com/b7596db53c234aac58f8b7e133433d179203982c15e3f2e13c5de63c4543a9bd.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
  return Deno.dlopen(file, symbols);
              ^
    at Object.opSync (deno:core/01_core.js:170:12)
    at new DynamicLibrary (deno:ext/ffi/00_ffi.js:256:40)
    at Object.dlopen (deno:ext/ffi/00_ffi.js:329:12)
    at Module.prepare (https://deno.land/x/plug@0.5.1/plug.ts:106:15)
    at async Function.create (https://deno.land/x/reedline_deno@0.9.0/src/mod.ts:45:17)
    at async file:///Users/jeremy/tmp/deno-test/index.ts:3:12
```

I'm sorry if I'm reporting many things 😄

**Comment by sigmaSd** [comment]
It's opposite thanks for taking the time to report the issue!

You're running on an arm system (on windows?)? I might need to add that architecture to the ci

**Comment by targetlucked69** [comment]
I'm using Monterey v12.4 on an M1 Pro 😃

**Comment by sigmaSd** [comment]
Ok until I figure out how to add m1 to the ci builds you can 
- clone the repo 
- `CARGO_TARGET_DIR=$PWD/target deno task example` (this is bash syntax)

**Comment by targetlucked69** [comment]
> Ok until I figure out how to add m1 to the ci builds you can
> 
> * clone the repo
> * `CARGO_TARGET_DIR=$PWD/target deno task example` (this is bash syntax)

This works, thanks!

**Comment by sigmaSd** [comment]
I added the m1 build, can you try the 0.10.0 version
```ts
import { ReedLine } from "https://deno.land/x/reedline_deno@0.10.0/src/mod.ts";

const rl = await ReedLine.create();

while (true) {
  const line = await rl.readLine({
    render_prompt_left: "> ",
    render_prompt_right: "<",
  });
  if (line.signal === "CtrlC") {
    console.log("CtrlC");
    break;
  }
  if (line.signal === "CtrlD") {
    console.log("CtrlD");
    break;
  }
  console.log(line.value);
}
```

**Comment by targetlucked69** [comment]
working now! Thanks @sigmaSd legend

**Comment by targetlucked69** [comment]
Another question if you don't mind me asking.. what's the difference if we just implement readline from Deno directly? Or we don't have that functionality yet that's why you made one via ffi?

**Comment by sigmaSd** [comment]
Yes exactly building a readline library is a respectable amount of work, so this is just a stop gap until one is created.
